/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alunniclassesql;

/**
 *
 * @author onorati.nicolo
 */
public class AggiungiElimina extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiungiElimina.class.getName());
    Gestore g = new Gestore();

    /**
     * Creates new form AggiungiElimina
     */
    public AggiungiElimina() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_aggiungi = new javax.swing.JButton();
        btn_elimina = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_scegliAlunno = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_aggiungi.setText("AGGIUNGI");
        btn_aggiungi.addActionListener(this::btn_aggiungiActionPerformed);

        btn_elimina.setText("ELIMINA");

        btn_home.setText("HOME");
        btn_home.addActionListener(this::btn_homeActionPerformed);

        txtA_scegliAlunno.setColumns(20);
        txtA_scegliAlunno.setRows(5);
        txtA_scegliAlunno.setText("Nome, Cognome, Classe\nES: Mario, Rossi, 5D");
        jScrollPane1.setViewportView(txtA_scegliAlunno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_elimina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_aggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_aggiungi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_elimina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_home)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        Interfaccia i = new Interfaccia();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_aggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggiungiActionPerformed
        String testo = txtA_scegliAlunno.getText();
        String parti[] = testo.split(",");
        if (parti.length == 3) {
            String nome = parti[0].trim();
            String cognome = parti[1].trim();
            String idClasse = parti[2].trim();

            if (g.aggiungiAlunno(nome, cognome, idClasse)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Alunno " + nome + " aggiunto alla classe " + idClasse);
                txtA_scegliAlunno.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Errore durante l'inserimento nel database.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Formato errato! Usa: Nome, Cognome, ID_Classe\nEsempio: Mario, Rossi, 1");
        }

    }//GEN-LAST:event_btn_aggiungiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AggiungiElimina().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aggiungi;
    private javax.swing.JButton btn_elimina;
    private javax.swing.JButton btn_home;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA_scegliAlunno;
    // End of variables declaration//GEN-END:variables
}
