/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alunniclassesql;

import java.util.ArrayList;

/**
 *
 * @author onorati.nicolo
 */
public class InterfacciaGite extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaGite.class.getName());
    Gestore g = new Gestore();
    /**
     * Creates new form InterfacciaGite
     */
    public InterfacciaGite() {
        initComponents();
        this.aggiornaGite();
        
        txtA_gite.setText(""); 
    
    ArrayList<String> partecipanti = g.leggiPartecipazioneGita();

    if (partecipanti.isEmpty()) {
        txtA_gite.setText("Nessun partecipante trovato.");
    } else {
        for (String s : partecipanti) {
            txtA_gite.append(s + "\n");
        }
    } 
    }
    public void aggiornaGite() {
    Object selezionato = cmb_scegliGita.getSelectedItem();
    if (selezionato == null) {
        return;
    }

    txtA_mostraGite.setText("");

    String gitaSelezionata = selezionato.toString();
    ArrayList<String> partecipanti = g.leggiPartecipazioneGitaSpecifica(gitaSelezionata);

    for (String s : partecipanti) {
        txtA_mostraGite.append(s + "\n");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_gite = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cmb_scegliGita = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_mostraGite = new javax.swing.JTextArea();
        btn_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtA_gite.setColumns(20);
        txtA_gite.setRows(5);
        jScrollPane1.setViewportView(txtA_gite);

        jLabel1.setText("ELENCO ALUNNI CHE PARTECIPANO AD UNA GITA");

        cmb_scegliGita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Firenze", "Roma", "Venezia", "Milano", "Napoli", "Torino", "Bologna" }));
        cmb_scegliGita.addActionListener(this::cmb_scegliGitaActionPerformed);

        txtA_mostraGite.setColumns(20);
        txtA_mostraGite.setRows(5);
        jScrollPane2.setViewportView(txtA_mostraGite);

        btn_home.setText("HOME");
        btn_home.addActionListener(this::btn_homeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(cmb_scegliGita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home)
                .addGap(421, 421, 421))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmb_scegliGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
       Interfaccia i = new Interfaccia();
       i.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_btn_homeActionPerformed

    private void cmb_scegliGitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_scegliGitaActionPerformed
        this.aggiornaGite();
    }//GEN-LAST:event_cmb_scegliGitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacciaGite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JComboBox<String> cmb_scegliGita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtA_gite;
    private javax.swing.JTextArea txtA_mostraGite;
    // End of variables declaration//GEN-END:variables
}
